from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

class Phase(str, Enum):
    NEW="NEW"; INTAKE="INTAKE"; SIZE="SIZE"; RESEARCH="RESEARCH"; BRAINSTORM="BRAINSTORM"; DECIDE="DECIDE"; TEST_DESIGN="TEST_DESIGN"; PLAN="PLAN"; PLAN_REVIEW="PLAN_REVIEW"; READY_TO_BUILD="READY_TO_BUILD"; IMPLEMENT="IMPLEMENT"; TEST_AUTHOR="TEST_AUTHOR"; TEST_EXECUTE="TEST_EXECUTE"; CODE_REVIEW="CODE_REVIEW"; DOCUMENT="DOCUMENT"; ALIGNMENT="ALIGNMENT"; ACCEPTANCE="ACCEPTANCE"; COMPLETE="COMPLETE"; DIAGNOSE="DIAGNOSE"; WAITING_HUMAN="WAITING_HUMAN"; WAITING_JOB="WAITING_JOB"; ESCALATED="ESCALATED"; FAILED="FAILED"; CANCELLED="CANCELLED"

class RunStatus(str, Enum):
    """Execution status, tracked independently of workflow phase."""
    CANCEL_REQUESTED="CANCEL_REQUESTED"; RECONCILIATION_REQUIRED="RECONCILIATION_REQUIRED"; ACTIVE="ACTIVE"; WAITING_HUMAN="WAITING_HUMAN"; WAITING_JOB="WAITING_JOB"; BLOCKED="BLOCKED"; FAILED="FAILED"; COMPLETE="COMPLETE"; SIMULATED="SIMULATED"; CANCELLED="CANCELLED"

# Explicit compatibility aliases: one shared invocation contract.
from agent_core.providers.base import Invocation, InvocationResult, ToolCall, TokenUsage
