#!/usr/bin/env python3
"""Project ide-agents/canonical/*.md into IDE-specific agent files.

Usage (from repository root):
  python ide-agents/scripts/sync_ide_agents.py
  python ide-agents/scripts/sync_ide_agents.py --check
  python ide-agents/scripts/sync_ide_agents.py --verbose

Edit canonical/ only; never hand-edit generated projections.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

try:
    import yaml  # type: ignore
except ImportError:  # pragma: no cover - minimal fallback
    yaml = None  # type: ignore

from _repo_layout import REPO_ROOT, ide_pack_root  # type: ignore[import-not-found]

IDE_PACK_ROOT = ide_pack_root()
CANONICAL_DIR = IDE_PACK_ROOT / "canonical"
MANIFEST_PATH = IDE_PACK_ROOT / "MANIFEST.yml"

FRONTMATTER_RE = re.compile(r"\A---\r?\n(.*?)\r?\n---\r?\n(.*)\Z", re.DOTALL)

DEFAULT_SKIP = {"README.md"}
READONLY_DISALLOW_CURSOR = (
    "Write",
    "StrReplace",
    "Delete",
    "EditNotebook",
    "Shell",
)
READONLY_DISALLOW_CLAUDE = (
    "Write",
    "Edit",
    "MultiEdit",
    "NotebookEdit",
    "Bash",
)
DEFAULT_VSCODE_TOOLS = ("search/codebase", "web/fetch", "read/readFile")


@dataclass(frozen=True)
class CanonicalAgent:
    stem: str
    path: Path
    frontmatter: dict[str, Any]
    body: str

    @property
    def name(self) -> str:
        raw = self.frontmatter.get("name")
        if isinstance(raw, str) and raw.strip():
            return raw.strip()
        return self.stem


def _load_manifest() -> dict[str, Any]:
    if not MANIFEST_PATH.is_file():
        return {}
    text = MANIFEST_PATH.read_text(encoding="utf-8")
    if yaml is None:
        return _parse_manifest_minimal(text)
    data = yaml.safe_load(text) or {}
    return data if isinstance(data, dict) else {}


def _parse_manifest_minimal(text: str) -> dict[str, Any]:
    """Parse skip list without PyYAML."""
    skip: list[str] = list(DEFAULT_SKIP)
    in_skip = False
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("skip_canonical_basenames:"):
            in_skip = True
            continue
        if in_skip:
            if stripped.startswith("- "):
                skip.append(stripped[2:].strip())
            elif stripped and not stripped.startswith("#"):
                in_skip = False
    return {"sync": {"skip_canonical_basenames": skip}}


def _parse_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}, text
    fm_raw, body = match.group(1), match.group(2)
    if yaml is not None:
        loaded = yaml.safe_load(fm_raw) or {}
        if not isinstance(loaded, dict):
            loaded = {}
        return loaded, body.lstrip("\n")
    return _parse_simple_frontmatter(fm_raw), body.lstrip("\n")


def _parse_simple_frontmatter(fm_raw: str) -> dict[str, Any]:
    """Flat key: value parser when PyYAML is unavailable."""
    out: dict[str, Any] = {}
    for line in fm_raw.splitlines():
        if ":" not in line or line.strip().startswith("#"):
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip().strip('"').strip("'")
        if val.lower() in ("true", "false"):
            out[key] = val.lower() == "true"
        else:
            out[key] = val
    return out


def _skip_basenames(manifest: dict[str, Any]) -> set[str]:
    sync = manifest.get("sync") or {}
    skip = sync.get("skip_canonical_basenames") or []
    names = set(DEFAULT_SKIP)
    if isinstance(skip, list):
        names.update(str(x) for x in skip)
    return names


def _discover_canonical(manifest: dict[str, Any]) -> list[CanonicalAgent]:
    skip = _skip_basenames(manifest)
    agents: list[CanonicalAgent] = []
    if not CANONICAL_DIR.is_dir():
        return agents
    for path in sorted(CANONICAL_DIR.glob("*.md")):
        if path.name in skip or path.name.startswith("_"):
            continue
        text = path.read_text(encoding="utf-8")
        fm, body = _parse_frontmatter(text)
        agents.append(CanonicalAgent(stem=path.stem, path=path, frontmatter=fm, body=body))
    return agents


def _banner(manifest: dict[str, Any], name: str) -> str:
    sync = manifest.get("sync") or {}
    template = sync.get("generated_banner")
    if isinstance(template, str):
        return template.format(name=name).rstrip() + "\n\n"
    return (
        f"<!-- GENERATED by ide-agents/scripts/sync_ide_agents.py — do not edit -->\n"
        f"<!-- source: ide-agents/canonical/{name}.md -->\n\n"
    )


def _is_readonly(fm: dict[str, Any]) -> bool:
    if "readonly" in fm:
        return bool(fm["readonly"])
    authority = str(fm.get("authority", "")).lower()
    if authority in ("read-only", "readonly", "diagnostic"):
        return True
    if authority == "implementation":
        return False
    return True


@dataclass(frozen=True)
class ProjectionTargets:
    cursor_dir: Path
    claude_dir: Path
    vscode_dir: Path
    cursor_pattern: str
    claude_pattern: str
    vscode_pattern: str


def _projection_targets(manifest: dict[str, Any]) -> ProjectionTargets:
    projections = manifest.get("projections") or {}
    defaults = {
        "cursor": (".cursor/agents", "{name}.md"),
        "claude": (".claude/agents", "{name}.md"),
        "vscode": (".github/agents", "{name}.agent.md"),
    }
    dirs: dict[str, Path] = {}
    patterns: dict[str, str] = {}
    for key, (rel, pattern) in defaults.items():
        block = projections.get(key) or {}
        rel_dir = block.get("rel_dir", rel)
        filename_pattern = block.get("filename_pattern", pattern)
        dirs[key] = REPO_ROOT / str(rel_dir).replace("\\", "/")
        patterns[key] = str(filename_pattern)
    return ProjectionTargets(
        cursor_dir=dirs["cursor"],
        claude_dir=dirs["claude"],
        vscode_dir=dirs["vscode"],
        cursor_pattern=patterns["cursor"],
        claude_pattern=patterns["claude"],
        vscode_pattern=patterns["vscode"],
    )


def _render_cursor(agent: CanonicalAgent, manifest: dict[str, Any]) -> str:
    fm = dict(agent.frontmatter)
    readonly = _is_readonly(fm)
    fm.setdefault("name", agent.name)
    fm.setdefault("description", f"IDE agent {agent.name} (canonical projection)")
    fm["readonly"] = readonly
    if readonly and "tools" not in fm:
        fm["tools"] = {"deny": list(READONLY_DISALLOW_CURSOR)}
    body = _banner(manifest, agent.stem) + agent.body.strip() + "\n"
    if yaml is None:
        raise RuntimeError("PyYAML is required for projection; pip install pyyaml")
    return "---\n" + yaml.safe_dump(fm, sort_keys=False, allow_unicode=True).rstrip() + "\n---\n\n" + body


def _render_claude(agent: CanonicalAgent, manifest: dict[str, Any]) -> str:
    fm = dict(agent.frontmatter)
    readonly = _is_readonly(fm)
    name = agent.name
    description = str(fm.get("description", f"IDE agent {name}"))
    disallowed = fm.get("disallowedTools")
    if disallowed is None and readonly:
        disallowed = list(READONLY_DISALLOW_CLAUDE)
    claude_fm: dict[str, Any] = {
        "name": name,
        "description": description,
        "readonly": readonly,
    }
    if disallowed is not None:
        claude_fm["disallowedTools"] = disallowed
    allowed = fm.get("allowedTools")
    if allowed is not None:
        claude_fm["allowedTools"] = allowed
    for key in ("authority", "contract_version", "skill_refs", "user_invocable"):
        if key in fm:
            claude_fm[key] = fm[key]
    body = _banner(manifest, agent.stem) + agent.body.strip() + "\n"
    return "---\n" + yaml.safe_dump(claude_fm, sort_keys=False, allow_unicode=True).rstrip() + "\n---\n\n" + body


def _render_vscode(agent: CanonicalAgent, manifest: dict[str, Any]) -> str:
    fm = dict(agent.frontmatter)
    readonly = _is_readonly(fm)
    name = agent.name
    vscode_fm: dict[str, Any] = {
        "name": name,
        "description": str(fm.get("description", f"IDE agent {name}")),
    }
    tools = fm.get("tools")
    if tools is None:
        vscode_fm["tools"] = list(DEFAULT_VSCODE_TOOLS)
    else:
        vscode_fm["tools"] = tools
    if "user_invocable" in fm:
        vscode_fm["user-invocable"] = fm["user_invocable"]
    elif fm.get("user-invocable") is not None:
        vscode_fm["user-invocable"] = fm["user-invocable"]
    else:
        vscode_fm["user-invocable"] = False
    if "handoffs" in fm:
        vscode_fm["handoffs"] = fm["handoffs"]
    if "agents" in fm:
        vscode_fm["agents"] = fm["agents"]
    if readonly:
        vscode_fm["readonly"] = True
    for key in ("authority", "contract_version", "skill_refs", "hooks"):
        if key in fm:
            vscode_fm[key] = fm[key]
    body = _banner(manifest, agent.stem) + agent.body.strip() + "\n"
    return "---\n" + yaml.safe_dump(vscode_fm, sort_keys=False, allow_unicode=True).rstrip() + "\n---\n\n" + body


def _render_all(agent: CanonicalAgent, manifest: dict[str, Any]) -> dict[str, str]:
    return {
        "cursor": _render_cursor(agent, manifest),
        "claude": _render_claude(agent, manifest),
        "vscode": _render_vscode(agent, manifest),
    }


def _target_path(targets: ProjectionTargets, ide: str, agent: CanonicalAgent) -> Path:
    if ide == "cursor":
        base, pattern = targets.cursor_dir, targets.cursor_pattern
    elif ide == "claude":
        base, pattern = targets.claude_dir, targets.claude_pattern
    else:
        base, pattern = targets.vscode_dir, targets.vscode_pattern
    return base / pattern.format(name=agent.stem)


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _write_text_lf(path: Path, content: str) -> None:
    """Write UTF-8 with LF line endings (Python 3.10-compatible)."""
    path.write_text(content.replace("\r\n", "\n"), encoding="utf-8")


def _managed_files(
    manifest: dict[str, Any], targets: ProjectionTargets, agents: list[CanonicalAgent]
) -> dict[Path, str]:
    managed: dict[Path, str] = {}
    for agent in agents:
        rendered = _render_all(agent, manifest)
        for ide in ("cursor", "claude", "vscode"):
            path = _target_path(targets, ide, agent)
            managed[path] = rendered[ide]
    return managed


def _orphan_generated(targets: ProjectionTargets, managed: dict[Path, str]) -> list[Path]:
    orphans: list[Path] = []
    for ide, base, glob in (
        ("cursor", targets.cursor_dir, "*.md"),
        ("claude", targets.claude_dir, "*.md"),
        ("vscode", targets.vscode_dir, "*.agent.md"),
    ):
        if not base.is_dir():
            continue
        for path in base.glob(glob):
            if path.name == ".gitkeep":
                continue
            text = path.read_text(encoding="utf-8")
            if "GENERATED by ide-agents/scripts/sync_ide_agents.py" not in text:
                continue
            if path not in managed:
                orphans.append(path)
    return orphans


def run_sync(check: bool, verbose: bool) -> int:
    manifest = _load_manifest()
    agents = _discover_canonical(manifest)
    targets = _projection_targets(manifest)

    for base in (targets.cursor_dir, targets.claude_dir, targets.vscode_dir):
        base.mkdir(parents=True, exist_ok=True)

    managed = _managed_files(manifest, targets, agents)
    mismatches: list[str] = []
    written = 0

    for path, content in sorted(managed.items(), key=lambda x: str(x[0])):
        if path.is_file():
            existing = path.read_text(encoding="utf-8")
            if existing != content:
                mismatches.append(str(path.relative_to(REPO_ROOT)))
                if not check:
                    _write_text_lf(path, content)
                    written += 1
        else:
            mismatches.append(str(path.relative_to(REPO_ROOT)))
            if not check:
                _write_text_lf(path, content)
                written += 1

    orphans = _orphan_generated(targets, managed)
    for path in orphans:
        mismatches.append(f"{path.relative_to(REPO_ROOT)} (stale generated)")
        if not check:
            path.unlink()
            written += 1

    if verbose:
        print(f"Canonical agents: {len(agents)}")
        for a in agents:
            print(f"  - {a.stem}")
        print(f"Managed projection files: {len(managed)}")

    if check:
        if mismatches:
            print("sync --check: out of date or missing:", file=sys.stderr)
            for m in mismatches:
                print(f"  {m}", file=sys.stderr)
            return 1
        print("sync --check: OK")
        return 0

    if verbose:
        print(f"Wrote or updated {written} projection file(s)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if projections differ from canonical (CI gate)",
    )
    parser.add_argument("--verbose", action="store_true", help="Print discovery details")
    args = parser.parse_args()
    manifest = _load_manifest()
    agents = _discover_canonical(manifest)
    if yaml is None and agents:
        print(
            "Error: PyYAML is required when canonical agents exist (pip install pyyaml).",
            file=sys.stderr,
        )
        return 2
    if yaml is None and not args.check:
        print(
            "Warning: PyYAML not installed; install pyyaml before adding canonical agents.",
            file=sys.stderr,
        )
    return run_sync(check=args.check, verbose=args.verbose)


if __name__ == "__main__":
    raise SystemExit(main())
